### ISSUE TITLE
Report APA style validity

### ISSUE THREAD

**Issue by nico202** [MicheleNuijten/statcheck#25]
It would be nice to have a dataframe variable saying whether the parsed "formula" is in valid APA style.
A simple way to reach it would be to match `$Raw` with the valid-APA regex

**Comment by MicheleNuijten** [comment]
Sorry for the extremely late reply (I wasn't really in the habit of checking issues on GitHub, something I will definitely change!).

Thanks for your suggestion, but in its current form, this wouldn't be informative in statcheck. Everything statcheck extracts is per definition in APA style, otherwise it wouldn't have matched the regex. This could be a useful feature if statcheck would also pick up non-APA stats.
