### ISSUE TITLE
Use of other characters as decimal separators

### ISSUE THREAD

**Issue by heelgueta** [MicheleNuijten/statcheck#27]
Some languages use the comma as a decimal separator. For instance, in some journals written in Spanish, it is recommended that results should be written as... "F(1, 19) = 4,44, p = 0,048". I was not able to extract results from such papers using statcheck. It would be nice if this could be somehow considered.

**Comment by MicheleNuijten** [comment]
Hi, good point. At the moment, I deliberately chose to only extract stats reported exactly in APA style, to keep the inclusion/exclusion criteria as clear as possible. However, I'm thinking of expanding statcheck to other reporting styles, which could include square brackets instead of parentheses for degrees of freedom for instance, but also your suggestion of commas as decimal separators would be a good addition.
